#!/bin/bash

pprint (){
	cred='\033[0;31m'
	cgreen='\033[0;32m'
	cyellow='\033[0;33m'
	cblue='\033[0;34m'
	cpurple='\033[0;35m'
	eval "export color='$cpurple'"
	[ ! -z $2 ] && eval "export color=\"\$$2\""
    printf "$color $1"
}

color_reset(){ printf '\033[0;37m'; }

yesnoprompt(){
	old_stty_cfg=$(stty -g)
	stty raw -echo ; answer=$(head -c 1)
	stty $old_stty_cfg
	echo "$answer" | grep -iq "^y"
}

update() {
	pprint "\n\nUpdating package list.. "
	sudo apt update 2>&1 | grep "can be upgraded" &>/dev/null
	if [ $? -eq 0 ]; then
		pprint "UPDATE AVAILABLE" "cgreen"
		pprint "\n\nDo you want to automatically upgrade (y/n)?"
		if yesnoprompt; then
			pprint "\n\nUpgrading packages.. "
			sudo apt upgrade -y &>/dev/null &&
			pprint "DONE!\n\n" "cgreen" || (pprint "FAIL.\n\n" "cred"; exit 1)
		else
			echo
		fi
	else
		pprint "ALREADY UP TO DATE\n\n" "cgreen"
	fi
}

dependencies() {
	if ! command -v pip &>/dev/null; then
		pprint "Couldn't find pip, installing now..."
		sudo apt install python3-pip -y 2>errorlog.txt 1>/dev/null &&
		pprint "SUCCESS.\n\n" "cgreen" || (pprint "FAIL.\n\n" "cred"; exit 1)
	fi

	pprint "\n\nInstalling required Python libraries...\n"
	pip3 install telebot flask aiogram pyTelegramBotAPI &>>errorlog.txt &&
	pprint "Libraries installed successfully.\n\n" "cgreen" || (pprint "FAIL.\n\n" "cred"; exit 1)
}

clear
pprint "Welcome to the Bot Setup Installer\n\n"
pprint "This script requires sudo privileges to update & install packages.\n"
sudo test

update
dependencies
pprint "\n\nSetup Completed Successfully!\n" "cgreen"
sleep 1
clear

pprint "\nEnter your environment variables below:\n\n\n"
pprint "BOT TOKEN: "; color_reset; read bot_token
pprint "\nADMIN ID: "; color_reset; read admin_id

pprint "\n\nSaving your variables...\n" "cgreen"

if [ -f .env ]; then
	rm .env
fi

echo """BOT_TOKEN=$bot_token
ADMIN_ID=$admin_id""" > .env

pprint "\n\nYour variables have been saved successfully!\n"
pprint "You can now start the bot by running: bash start.sh\n\n"
